# Generated by Django 5.2.1 on 2025-05-21 11:32

import markdownx.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_event_owner_file_owner_group_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True),
        ),
    ]
