# Generated by Django 5.2.1 on 2025-05-21 11:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_alter_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
    ]
