# Generated by Django 5.2.1 on 2025-05-21 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
