# Generated by Django 5.2.1 on 2025-05-21 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_alter_file_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='description',
            new_name='content',
        ),
    ]
