# Generated by Django 5.2.1 on 2025-05-21 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_rename_description_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
