# Generated by Django 5.2.1 on 2025-05-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0011_rename_description_file_notes_alter_file_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='date_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
