# Generated by Django 5.2.1 on 2025-05-22 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_group_date_end_group_date_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='date_end_approx_level',
            field=models.CharField(choices=[('none', 'Exact'), ('day', 'Approximate day'), ('week', 'Approximate week'), ('month', 'Approximate month'), ('year', 'Approximate year'), ('unknown', 'Unknown/very vague')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='group',
            name='date_start_approx_level',
            field=models.CharField(choices=[('none', 'Exact'), ('day', 'Approximate day'), ('week', 'Approximate week'), ('month', 'Approximate month'), ('year', 'Approximate year'), ('unknown', 'Unknown/very vague')], default='none', max_length=10),
        ),
    ]
