# Generated by Django 5.2.1 on 2025-05-22 11:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_alter_group_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
