# Generated by Django 5.2.1 on 2025-05-22 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0017_tag_alter_event_description_alter_event_details_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='content',
            new_name='information',
        ),
        migrations.AddField(
            model_name='file',
            name='summary',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
