# Generated by Django 5.2.1 on 2025-05-22 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0018_rename_content_file_information_file_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='date_approx_level',
            field=models.CharField(choices=[('none', 'Exact'), ('day', 'Approximate day'), ('week', 'Approximate week'), ('month', 'Approximate month'), ('year', 'Approximate year'), ('unknown', 'Unknown/very vague')], default='none', max_length=10),
        ),
    ]
