# Generated by Django 5.2.1 on 2025-06-03 08:52

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0019_uploadeddocument_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='timeline.file'),
        ),
        migrations.AlterField(
            model_name='file',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Practical informations'),
        ),
    ]
