# Generated by Django 5.2.1 on 2025-06-04 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0021_remove_event_group_alter_event_file_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
