# Generated by Django 5.2.1 on 2025-06-10 12:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0023_alter_file_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='details',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
