# Generated by Django 5.2.1 on 2025-06-10 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0024_file_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='timeline.file'),
        ),
    ]
