# Generated by Django 5.2.1 on 2025-06-16 07:41

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0028_alter_comment_comment_alter_comment_content_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalEntities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('type', models.CharField(choices=[('company', 'Company'), ('property', 'Approximate day')], default='none', max_length=10)),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
    ]
