# Generated by Django 5.2.1 on 2025-06-16 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0029_legalentities_alter_comment_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentities',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='legal_entities', to='timeline.tag'),
        ),
    ]
