# Generated by Django 5.2.1 on 2025-06-16 08:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0031_legalentities_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalentities',
            name='structure',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
