# Generated by Django 5.2.1 on 2025-06-16 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0032_legalentities_structure'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LegalEntities',
            new_name='Entities',
        ),
    ]
