# Generated by Django 5.2.1 on 2025-06-16 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0033_rename_legalentities_entities'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entities',
            new_name='Entity',
        ),
    ]
