# Generated by Django 5.2.1 on 2025-06-16 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0034_rename_entities_entity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name_plural': 'Entities'},
        ),
        migrations.AddField(
            model_name='file',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
