# Generated by Django 5.2.1 on 2025-06-17 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0036_file_active_file_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadeddocument',
            name='description',
            field=models.CharField(max_length=200),
        ),
    ]
