# Generated by Django 5.2.1 on 2025-06-17 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0037_alter_uploadeddocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
